### ISSUE TITLE
Image Missing /videodetector//icons/icon_black.png?t=H0CG

### ISSUE THREAD

**Issue by redbrad0** [dimitriconejo/videodetector#5]
I just downloaded the software to try it out and uploaded the zip file to our testing server. Uploading the software and then just viewing the page ?

http://beta.stubwire.com/_temp/testing/ckeditor/samples/index.html I get the below 404 error and the video icon is not visible.

ckeditor.js:94 GET ?http://beta.stubwire.com/_temp/testing/ckeditor/plugins/videodetector//icons/icon_black.png?t=H0CG 404 (Not Found)

**Comment by jpehman** [comment]
The issue is caused by an additional '/' in the path.

I'm going to do a pull request on this, but in the mean time, you could search "videodetector" in ckeditor.js and remove the extra '/' before "icons/icon_black.png" as well as before "videodetector.css".

**Comment by dimitriconejo** [comment]
Thank you. I fix the paths.

**Comment by jpehman** [comment]
awesome

Best Regards,

Jonathan Ehman

**Comment by mbomb007** [comment]
This is still not fixed. See this CKEditor build: https://ckeditor.com/cke4/builder/6a246337be5df0b78c79d553406e7262

The entire icons folder is missing in the download.
