### ISSUE TITLE
There is no icon in the toolbar

### ISSUE THREAD

**Issue by teddydoors** [dimitriconejo/videodetector#8]

**Comment by mbomb007** [comment]
The icons folder is not downloaded when using [CKEditor's builder](https://ckeditor.com/cke4/builder). You can download the files manually from Github for now.

Hopefully the owner will fix the add-on to have the folder.

**Comment by teddydoors** [comment]
Thanks, I  figured out that on the first day.

**Comment by mbomb007** [comment]
We should leave an issue open so he knows to fix it. I made a new one: https://github.com/dimitriconejo/videodetector/issues/10
